### ISSUE TITLE
Suggestion: Copy-Paste feature

### ISSUE THREAD

**Issue by loehnertj** [huskcasaca/effortless#11]
This mod is great! One additional feature that would be uber-cool would be copy-pasting of block regions.

Could work like this:

- select copy mode
- mark block region with one of the existing tools
- get a "blueprint" (special item) that you can place in the hotbar
- "use" the blueprint item to place copies of the region anywhere

**Comment by huskcasaca** [comment]
Okay copy and paste mode will be added but blueprint item will not. The blueprint will be achieve in UI instead of adding new item since this mod is designed to be a vanilla compatible one.

**Comment by loehnertj** [comment]
Sounds good, looking forward to it ;-)

**Comment by Telezhka-the-First** [comment]
This request is fulfilled actually. Issue should be closed.
