### ISSUE TITLE
Fabric 1.19.2 2.3.3 Crash

### ISSUE THREAD

**Issue by DemonSlayer112** [huskcasaca/effortless#110]
I dont know the cause but selecting Line preset and the radial preset seems to crash.
Loaded up fresh new client and world:

### Log
[latest.log](https://github.com/huskcasaca/effortless/files/15134100/latest.log)
### Crash
[crash-2024-04-26_11.19.08-client.txt](https://github.com/huskcasaca/effortless/files/15134102/crash-2024-04-26_11.19.08-client.txt)

**Comment by huskcasaca** [comment]
The radial one.
