### ISSUE TITLE
client crash when building on server 1.19.2

### ISSUE THREAD

**Issue by netcore10** [huskcasaca/effortless#15]
on latest effortless, client crashes with this after placing and breaking with any mode on my server. It works fine in singleplayer, but if i join MP and try to edit, my client crashes and i have to log on again

![image](https://user-images.githubusercontent.com/181536/210077014-c6c97cba-9d74-470b-9718-a195db2efe77.png)

https://paste.atlauncher.com/view/abb24b2d-3a79-49a3-97e1-6d98e0aef21b

**Comment by netcore10** [comment]
the logs do say something about audio but i'm quite confused

**Comment by netcore10** [comment]
Here's the server log, but it doesn't throw an error except on disconnect https://mclo.gs/uZOBOcI

**Comment by huskcasaca** [comment]
Try latest version.
