### ISSUE TITLE
Mod incompatibility with Dynamic Lights, cannot join Singleplayer world

### ISSUE THREAD

**Issue by Thedeur** [huskcasaca/effortless#161]
Upon trying to connect to a Singleplayer world with these two and Fabric API installed, it completely stops on the last step and shows "Connection Lost: Invalid Player Data", with the only option going back to the Multiplayer server list for whatever reason. 

Minecraft 1.20.4
Effortless 3.0.0
Fabric 0.97.1+1.20.4

[latest 2.log](https://github.com/user-attachments/files/16337223/latest.2.log)

**Comment by CConductor** [comment]
Same here, except on Forge 1.20.1-47.2.17, mod version still 3.0.0

**Comment by TheLethically** [comment]
is there a fix yet?
