### ISSUE TITLE
`ConcurrentModificationException: ThreadLocalRandom accessed from a different thread`

### ISSUE THREAD

**Issue by SettingDust** [huskcasaca/effortless#20]
Kicked from single player when place too far

`Internal Exception: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Thread[#105,Server thread,8,main], current: Thread[#126,Netty Acceptor IO Thread,5,main])`

**Comment by huskcasaca** [comment]
Noted, will fix in next release.

**Comment by ParodyVerse** [comment]
Just want to say I get the same issue but with breaking any blocks (Even just twelve in total). I can break six, but then if I break more it gives me the error.

**Comment by darloth** [comment]
I have this issue when breaking any more than a single block at a time using any of the effortless building modes.  It builds ok though.

**Comment by ZcytheGaming** [comment]
Getting this error alot, Do not see 1.6.3 anywhere?

**Comment by huskcasaca** [comment]
[Check the release](https://github.com/huskcasaca/effortless-fabric/releases/tag/v1.6.3)
