### ISSUE TITLE
unused strings in en_us.json

### ISSUE THREAD

**Issue by xlifi** [huskcasaca/effortless#22]
for example effortless.settings.max_block_total.title is unused in the mod but exists in language file. are those features going to be implemented?

im translating and missing context

**Comment by huskcasaca** [comment]
Not sure. I think you can start translating in next version 1.7.0 because some texts haven't been extracted to the language file.

**Comment by Telezhka-the-First** [comment]
Could you remove unused strings? This would simplify translation a lot.
