### ISSUE TITLE
Just wanna ask: Does it/Will it support ViaVersion (ViaFabric), ViaBackwards and ViaRewind?

### ISSUE THREAD

**Issue by shadichy** [huskcasaca/effortless#26]

**Comment by huskcasaca** [comment]
Not sure, but it should work if both sides have installed effortless.

**Comment by shadichy** [comment]
one more question: i have a forge server with eb installed, which version is lower than my fabric client, anh when I try connecting, it shows mod incompatible

**Comment by huskcasaca** [comment]
No effortless rewrote most of the code in eb and fixed lots of bugs so they’re no longer compatible with each other. I plan create a forge and paper versions of effortless after the release of  effortless 1.7.0.

**Comment by huskcasaca** [comment]
Yes it is supported now.
