### ISSUE TITLE
actionbar messages not shown with this mod enabled

### ISSUE THREAD

**Issue by Lpkuba088** [huskcasaca/effortless#27]
Minecraft version: 1.19.3
Fabric version: 0.14.14
Fabric API version:0.75.1
Effortless Fabric version: 1.6.2
Tested with other versions?: No
Other mods?: MTR(tried without aswell, clear multimc instance, still the same thing happens)
Steps to reproduce: /title @a actionbar {"text":"Hello world!"}
Expected behavior: Displays Hello World! above the hotbar

**Comment by SzczurekYT** [comment]
I checked the code trying to fix this myself, and I'm _impressed_, you managed to break something without even touching it. I thought it will be a something simple like a mixin adding an early return or something like that, but there's only one unrealted inject at the end of the method.
At least this is reproducible in the dev env.

**Comment by huskcasaca** [comment]
Oh the text covering bug is already fixed in 1.6.3 two months ago but I have not released it yet. You can rebuild that branch and I will release it later~

**Comment by huskcasaca** [comment]
https://github.com/huskcasaca/effortless-fabric/releases/tag/v1.6.3
