### ISSUE TITLE
Music and SFX reset after opening and closing radial menu

### ISSUE THREAD

**Issue by Hahahavana** [huskcasaca/effortless#28]
Not sure if version specific, but for reference using the latest 1.19.2 version on the latest Qulit Loader. 

If music or SFX are playing while you open the radial menu they will entirely cut out after closing. Music will not continue playing and continual SFX like rain will take a second or two to start up again, unlike say opening the main menu where it is just paused.

Not a gamebreaking issue, or even a major one, but it is a bit of a nitpick that can hurt the atmosphere while building.

**Comment by huskcasaca** [comment]
Noted. All bugs will be fixed in v1.7.0.
