### ISSUE TITLE
A small suggestion for building habits.

### ISSUE THREAD

**Issue by XieDeWu** [huskcasaca/effortless#31]
I'm sorry, if the logical order cannot be changed, please close this issue.
array functionality is abnormal, general building habits are mirror rotations and copies, not using 'mirror' for 'array'.
Here is additional code regarding the methods findCoordinates and findBlockStates in the BuildModifierHandler class.

//======Mirror first;Then Array;Append output;======
var mirror = new LinkedHashSet<>(List.of(blockPos));
mirror.addAll(Mirror.findCoordinates(player, blockPos));
mirror.addAll(RadialMirror.findCoordinates(player, blockPos));
var array = new LinkedHashSet<>(mirror);
for (var mir : mirror) {
    array.addAll(Array.findCoordinates(player, mir));
}
coordinates.addAll(array);
//=====================================

//======Mirror first;Then Array;Append output======
var mirrorBlockstates = new LinkedHashMap<BlockPos,BlockState>();
mirrorBlockstates.put(blockPos,blockState);
mirrorBlockstates.putAll(Mirror.findBlockStates(player, blockPos, blockState, itemStack, itemStacks));
mirrorBlockstates.putAll(RadialMirror.findBlockStates(player, blockPos, blockState, itemStack, itemStacks));
var arrayBlockstates = new LinkedHashMap<>(mirrorBlockstates);
for(Map.Entry<BlockPos,BlockState> entry: mirrorBlockstates.entrySet()){
    arrayBlockstates.putAll(Array.findBlockStates(player, entry.getKey(), entry.getValue(), itemStack, itemStacks));
}
blockStates.putAll(arrayBlockstates);
//=====================================

**Comment by huskcasaca** [comment]
Thanks, I'm already working on that. New array, mirror and randomizer settings will be added in 1.7.0.
