### ISSUE TITLE
kicked from my sever when using this mod

### ISSUE THREAD

**Issue by jay43634** [huskcasaca/effortless#34]
![image](https://user-images.githubusercontent.com/129667190/229353416-49d274ca-6f28-4474-88db-92d27235dec5.png)

if you need any thing like the log or something just ask (only hapens when i destroy / place more then 20 - 30 block at a time

**Comment by Starlight-quality** [comment]
the same error, I tried to open the world to the network, it didn't work, the error log is empty, although I play in a single game, writes that I have a server with a lost connection :/

**Comment by Starlight-quality** [comment]
> та же ошибка, пробовал открыть мир по сети, не получилось, журнал ошибок пустой, хотя играю в одиночную игру, пишет что у меня сервер с потерянным соединением :/

https://github.com/huskcasaca/effortless-fabric/releases/tag/v1.6.3 try this
