### ISSUE TITLE
crash when hovering over the undo redo panel while pressing alt [Fabric 1.19.2 mod version 1.6.3]

### ISSUE THREAD

**Issue by Starlight-quality** [huskcasaca/effortless#38]
[Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (36 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: -805306369
flush now
[Launcher] [Crash] Signature "PermGen error" matches!
[Crash] Signature "PermGen error" matches!
[Launcher] [Crash] Crash has been recognized!
[Crash] Crash has been recognized!
flush now

I don't know what it might mean

**Comment by vinnyg0621** [comment]
wow, this is the exact same problem that I have but on 1.19.4!
