### ISSUE TITLE
使用光影的时候，预览的图形会不显示出来

### ISSUE THREAD

**Issue by wudidiyes** [huskcasaca/effortless#39]
### Describe the Bug

使用光影的时候，预览的图形会不显示出来

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![9SC66~ISX~VTJ)HXO DSUF4](https://github.com/huskcasaca/effortless-fabric/assets/140710070/4999e3b4-4d69-4bbe-b8d4-5de1e5d10c06)
![N1MOK% GE}$21 N929SR{6M](https://github.com/huskcasaca/effortless-fabric/assets/140710070/973a5f7f-2684-4a07-af36-38e54724fdb6)

### Minecraft Version

1.19.3

### Mod Version

1.6.2

### Fabric Version

0.14.21

### Operating System

windows10

**Comment by huskcasaca** [comment]
下一个版本会一并修复
