### ISSUE TITLE
Replace Function Crashes Game | 1.19.4 | 1.6.3

### ISSUE THREAD

**Issue by cmcguire951** [huskcasaca/effortless#41]
### Describe the Bug

When going to select the replace function the game immediately freezes and then crashes.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/huskcasaca/effortless-fabric/assets/135708603/1be1d1f2-84e4-45cd-90ee-8daef3134a91)

### Other Mods

![image](https://github.com/huskcasaca/effortless-fabric/assets/135708603/fd52cc4f-0954-400d-8937-8728b8328051)

### Minecraft Version

1.19.4

### Mod Version

1.6.3

### Fabric Version

0.14.22

### Operating System

Windows 10

**Comment by vinnyg0621** [comment]
exactly the same problem I have. why hasn't anyone helped us yet???
