### ISSUE TITLE
Suggestion: transfer copied structures between worlds.

### ISSUE THREAD

**Issue by Telezhka-the-First** [huskcasaca/effortless#46]
We already have functionality of copying and pasting structures, but only in the same world, as the structure origin. Could you make it so that I can paste structure from one world to another?

**Comment by loehnertj** [comment]
Hello Telezhka, would you mind opening this issue in my fork's issue tracker? https://github.com/loehnertj/effortless-fabric/issues

I'll keep in mind but it needs careful thought on how to store the structure data for the client. So don't expect this too soon.

**Comment by Telezhka-the-First** [comment]
Done.
