### ISSUE TITLE
Suggestion: air placement.

### ISSUE THREAD

**Issue by Telezhka-the-First** [huskcasaca/effortless#47]
It would be amazing if we could place air blocks with building modes from this mod (effectively removing blocks in the desired shape).

**Comment by loehnertj** [comment]
You can already break blocks by using the attack (Left) mouse button - which effectively replaces blocks by air - or do you mean something else?

**Comment by Telezhka-the-First** [comment]
Thanks, that's exactly what I meant. I was trying it with right mouse button & empty hand, that's why it didn't work for me the first time.
