### ISSUE TITLE
Bug: sound during structure placement.

### ISSUE THREAD

**Issue by Telezhka-the-First** [huskcasaca/effortless#48]
I copied a village well with a bell with "structure" mod, and every time it's preview location changed, the bell rung. It would be logical to make preview structures silent, since they don't actually exist in the world and therefore can't produce sounds.

**Comment by loehnertj** [comment]
Hello Telezhka, would you mind opening this issue in my fork's issue tracker? https://github.com/loehnertj/effortless-fabric/issues

I'll look into it.

**Comment by Telezhka-the-First** [comment]
Done.
