### ISSUE TITLE
This mod doesn't work in server side (1.19.2 Fabric)

### ISSUE THREAD

**Issue by ItBeKirito** [huskcasaca/effortless#49]
This mod was working yesterday but when i tried to launch my server again today, it doesnt work. The server only starts running when i disable the effortless fabric mod. any solutions to this problem?

![image](https://github.com/huskcasaca/effortless/assets/155316560/d551537f-93c8-4b53-a71f-7c700eaa41cc)

Methods i tried that didnt work:
1. Tried diff versions like 1.19.2 and 1.19.3 but both dont work in the server anymore.
2. Tried the outdated versions of the mod but also doesnt work.
3. This issue is only from the server side but when i tried launching the game solo i have no issues, but i want it to work in the server side since most of my progress is from there.

**Comment by huskcasaca** [comment]
Looks like you upgraded your Fabric Loader to 0.15.2 and the deps in effortless is 0.14.x.

**Comment by ItBeKirito** [comment]
![image](https://github.com/huskcasaca/effortless/assets/155316560/160b2389-83ea-4686-ba53-b0e64c52821d)

the server only has these 2 fabric loaders and it was always on 0.15.2
I cant go back to 0.14 cuz it was never an option in Aternos. Is there another way to bypass this issue?

**Comment by ItBeKirito** [comment]
> Looks like you upgraded your Fabric Loader to 0.15.2 and the deps in effortless is 0.14.x.

Will there be an update to this mod for fabric loader 0.15.2 so dat the issue will b resolved?

**Comment by huskcasaca** [comment]
I will build you a working package later

**Comment by huskcasaca** [comment]
You can also unzip the jar package and remove this line `"fabricloader": "0.14.x"` in `fabric.mod.json` file, and simply compress them back to a jar file.

**Comment by ItBeKirito** [comment]
> You can also unzip the jar package and remove this line `"fabricloader": "0.14.x"` in `fabric.mod.json` file, and simply compress them back to a jar file.

unfortunately i cant configure the file through the server in aternos, there's no option to do that. The only option available to me is installing the mod.

**Comment by ItBeKirito** [comment]
> I will build you a working package later

Yes please do and thanks.. But do u have an estimated time of when itll come out thoe?

**Comment by huskcasaca** [comment]
Please try v2.0.0, it removes the limitation of fabricloader

**Comment by ItBeKirito** [comment]
> Please try the latest release, it removes the limitation of fabricloader

i tried version 1.19.4 and 1.19.2 but the issue still persist. 

![image](https://github.com/huskcasaca/effortless/assets/155316560/cb1fed50-070b-463a-a3ce-d718bc7fee66)

**Comment by huskcasaca** [comment]
The latest release is v2.0.0

**Comment by ItBeKirito** [comment]
> The latest release is v2.0.0

problem is im playing in mc 1.19.2 cuz most mods r still not available in the latest version. Will the latest release work on an older version of mc?

**Comment by huskcasaca** [comment]
https://github.com/huskcasaca/effortless/releases/tag/v2.0.0
