### ISSUE TITLE
Crash when press Alt

### ISSUE THREAD

**Issue by MaoDoBan** [huskcasaca/effortless#51]
The game crash (close) when I press Alt (to open the menu of Effortlhes).
I was with planks on hand, but on a second test I was without items on hand.
The /crash-reports folder is empty. 

I'm using:
effortless-fabric-1.20.4-2.0.0.jar (alpha 6 I suppose)
fabric-api-0.95.1+1.20.4.jar
fabric loader 0.15.6
launcher modrinth app

On other subject: in other test, with sodium, iris and some other mods, the game not load the maim menu on startup, visualy stuck at Mojang loading screen.

**Comment by huskcasaca** [comment]
Can you provide a mod list for the alt key holding crash?

**Comment by MaoDoBan** [comment]
Modlist:
effortless-fabric-1.20.4-2.0.0.jar (alpha 6 I suppose)
fabric-api-0.95.1+1.20.4.jar

On fabric loader 0.15.6

**Comment by lota09** [comment]
The same issue happens to me.
[crash.txt](https://github.com/huskcasaca/effortless/files/14099687/crash.txt)
