### ISSUE TITLE
Suggestion: support 1.20.1

### ISSUE THREAD

**Issue by MaoDoBan** [huskcasaca/effortless#52]
Create mod and other big/small popular mods rely only on 1.20.1 (on fabric and/or forge 1.20.X), this is why I suggest Effortless to support minecraft 1.20.1 too.

On other subject: discord invite on readme is a placeholder now, it is intended?

**Comment by huskcasaca** [comment]
Sure, porting to other versions is on the list. 

Yes it's a placeholder. I will add the discord link later.
