### ISSUE TITLE
Minecraft crashes on selecting the mod within the mod review menu in-game

### ISSUE THREAD

**Issue by Jirachi6774** [huskcasaca/effortless#63]
The game crashes big when you click on the mod in the mod selection screen within Minecraft.
![image](https://github.com/huskcasaca/effortless/assets/75322498/d6271038-0d94-4ce3-978b-46846668c88e)
![image](https://github.com/huskcasaca/effortless/assets/75322498/1dd86a1a-32c7-4682-a12a-893c88c54784)
If you click on the mod here it crashes the game very heavily, locking up fully before it force closes itself.

**Comment by huskcasaca** [comment]
Logs pls.

**Comment by Jirachi6774** [comment]
Crash Log when clicking on the Mod within the Mods Menu:
[crash-2024-02-24_13.33.37-client.txt](https://github.com/huskcasaca/effortless/files/14392815/crash-2024-02-24_13.33.37-client.txt)
