### ISSUE TITLE
Game crashes with Quilt

### ISSUE THREAD

**Issue by asoji** [huskcasaca/effortless#78]
Having a 1.20.1 Quilt 0.23.0 instance with QFAPI 7.5.0 + QSL 6.1.2 + FAPI 0.91.0 seems to crash the game entirely. Seems to be something with the PlatformLoader? Assumed the mod would work since Quilt for the most part can load Fabric mods fine.

Crash Log: https://mclo.gs/myeRuM6

**Comment by AlexIIL** [comment]
This could probably be fixed by treating quilt as fabric by adding
```java
if (loader.getClass().getPackageName().startsWith("org.quiltmc.")) {
    return LoaderType.FABRIC;
}
```
to https://github.com/huskcasaca/effortless/blob/a2fb51eb9359d4fecc8c461b95ac89c49d953b91/api/src/main/java/dev/huskuraft/effortless/api/platform/PlatformLoader.java#L129-L139
