### ISSUE TITLE
Makes Left Ctrl unusable on launch

### ISSUE THREAD

**Issue by Telezhka-the-First** [huskcasaca/effortless#79]
If I load a game with this mod, my character can't run via pressing Left Ctrl unless you rebind it (even to the same key). Upon saving changes to the keys, everything works fine until restarting the game, where you need to perform the same actions again.

Minecraft 1.20.4
Fabric 0.15.7
Effortless 2.2.0

**Comment by Rebilium** [comment]
same have to rebind it even though its there everytime i launch the game

**Comment by kaydenvg** [comment]
+1, have to rebind ctrl every launch

**Comment by MikiCZSK** [comment]
Can confirm, same here
