### ISSUE TITLE
Game crash upon attempted opening of build wheel

### ISSUE THREAD

**Issue by Courageousodin** [huskcasaca/effortless#84]
Hey all, been running a modpack for for a small group of people and recently added the mod to the pack. Went to go test the mod before releasing the pack update, but when pressing alt to open the wheel I immediately crashed. Tried rebinding to other keys and had the same issue. Tried downgrading the mod version from 2.2.0 to 2.1.0 and problem was solved, oddly enough. Crash log attached, would attach an export of the pack but github does not let me. 

Currently running Fabric 0.15.6 on MC version 1.19.2 

[2024-04-10-3.log](https://github.com/huskcasaca/effortless/files/14940107/2024-04-10-3.log)

**Comment by Courageousodin** [comment]
actually have a completely seperate problem now, for whatever reason effortless makes the JEI search bar unuseable. I click in on the search bar like normal but can't type anything. If i spam click on the search bar i can get maybe 1 character in before it stops letting me type. Best guess is that the mod is taking focus away from the search bar for whatever reason. Tested on both version 2.2.0 and 2.2.1; bug present on both versions.

**Comment by huskcasaca** [comment]
Can share the mod pack?

**Comment by huskcasaca** [comment]
Okay should be fixed in next release
