### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by MichelJonkman** [huskcasaca/effortless#92]
I can't find a configuration file and /effortless doesn't seem to exist, using 1.20.1 Forge

Also, the Discord invite is invalid so it might be a good idea to replace that.

**Comment by huskcasaca** [comment]
It will be released in 2.3.0

**Comment by MichelJonkman** [comment]
Has this already been implemented on the master branch? If so, is it possible to get a development build of it? I tried compiling it myself you seem to be using a plugin that can't resolve

**Comment by spookyroses** [comment]
how do you disable breaking blocks with effortless in survival mode?
