### ISSUE TITLE
Disconnected from server even though I play singleplayer

### ISSUE THREAD

**Issue by MuhammadZaid420** [huskcasaca/effortless#97]
First of all this is a really great mod. I would say top 5 must have, but I recently found an issue like the title said. I haven't got this kind of problem or "bug" in any other mod that ive installed. It seems that if you are using too much of the "Build Modes" feature it will disconnected the game and send me to the multiplayer server list. Again ive never join any multiplayer session. I f any one of you guys experience it or got any way to solved it I would like to know . Thanks cheers

**Comment by huskcasaca** [comment]
Logs or version pls. It should be fixed in latest release.

**Comment by MuhammadZaid420** [comment]
The version that I use is effortless-1.20.4-2.3.1. Im currently playing on fabric .

**Comment by huskcasaca** [comment]
Can provide the mod list?

**Comment by huskcasaca** [comment]
Also, is there any error messages when you got kicked out?

**Comment by MuhammadZaid420** [comment]
There is a massage but it happens rarely. Ive been "kicked" over like 10 times any 2 of them send me an error massage. Id try to replicate and send the code.

**Comment by DadamaldaDad** [comment]
I get kicked every time i undo a medium size area, the undo/redo performance is awful.
It wasn't even 500 blocks.

**Comment by MuhammadZaid420** [comment]
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "dev.huskuraft.effortless.api.core.BlockState.isAir()" because the return value of "dev.huskuraft.effortless.building.operation.block.BlockOperation.getBlockState()" is null


I just received this error message. The error message that was shown in game that I was talking about is rare. *i just reliezed that im typing massages instead of messages sorry about that.

**Comment by MuhammadZaid420** [comment]
Ive recognized a pattern that whenever Im using it too much or too frequently and too large *ie im using a lot of block within a large area it will crash.

**Comment by huskcasaca** [comment]
Try the latest release.
